import { BadgeCheck, Droplets, MapPin, ShieldCheck, Star, Wifi, Zap } from 'lucide-react'
import type { Property } from '../types/property'

type PropertyCardProps = { property: Property }

const serviceIcons = [Droplets, Zap, Wifi]

export default function PropertyCard({ property }: PropertyCardProps) {
  return <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-md"><div className="relative aspect-[16/10] overflow-hidden bg-slate-100"><img src={property.image} alt={property.title} className="size-full object-cover" loading="lazy" />{(property.available || property.verified) && <span className="absolute left-3 top-3 inline-flex items-center gap-1.5 rounded-full bg-secondary/10 px-3 py-1.5 text-xs font-bold text-secondary-dark shadow-sm">{property.verified ? <BadgeCheck size={14} aria-hidden="true" /> : <span className="size-1.5 rounded-full bg-secondary" />}{property.verified ? 'Verificado' : 'Disponible'}</span>}</div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-bold text-primary">{property.title}</h3><p className="mt-1 inline-flex items-center gap-1 text-sm text-neutral/80"><MapPin size={15} aria-hidden="true" />{property.location}</p></div><p className="shrink-0 text-right text-lg font-extrabold text-primary">${property.price}<span className="block text-xs font-normal text-neutral/70">/{property.currency} mes</span></p></div><div className="mt-4 flex items-center gap-2 rounded-xl bg-blue-50 px-3 py-2.5"><ShieldCheck size={19} className="text-primary" aria-hidden="true" /><div className="flex items-center gap-1"><Star size={15} className="fill-tertiary text-tertiary" aria-hidden="true" /><span className="font-bold text-primary">{property.rating.toFixed(1)}</span><span className="text-sm text-neutral/75">({property.reviews} reseñas)</span></div></div><div className="mt-4 flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-neutral/75">{serviceIcons.map((Icon, index) => <span key={property.services[index] ?? index} title={property.services[index]} className="grid size-8 place-items-center rounded-lg bg-slate-100"><Icon size={16} aria-hidden="true" /></span>)}</div><button type="button" className="text-sm font-bold text-secondary transition hover:text-secondary-dark">Ver detalles</button></div></div></article>
}
